In [1]:
import torch

ModuleNotFoundError: No module named 'torch'

In [ ]:
x=torch.tensor(3.0)
y=torch.tensor(2.0)
x+y,x*y,x/y,x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [ ]:
x=torch.arange(3)
x

tensor([0, 1, 2])

In [ ]:
x[2]

tensor(2)

In [ ]:
x.shape

torch.Size([3])

In [ ]:
A=torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Transposing a matrix

In [ ]:
A.T 

tensor([[0, 2, 4],
        [1, 3, 5]])

Symmetric matricse are subset of square matrices that are equal to their own transpose. 

In [ ]:
A=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A==A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
A=torch.arange(6,dtype=torch.float32).reshape(2,3)
B=A.clone() # Assign a copy of A to B by allocating new memory
A,A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [ ]:
A*B # hadamard product

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [ ]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Reduction

In [ ]:
x=torch.arange(3,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [ ]:
A.shape,A.sum()

(torch.Size([2, 3]), tensor(15.))

In [ ]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [ ]:
A.sum(axis=[0,1]) == A.sum() # Same as A.sum()

tensor(True)

In [ ]:
A.mean(axis=0),A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

### Non-Reduction Sum

In [ ]:
sum_A=A.sum(axis=1,keepdims=True)
A,A.shape,sum_A,sum_A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [ ]:
A/sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [ ]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

### Dot Products

In [ ]:
y=torch.ones(3,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [ ]:
torch.sum(x*y)

tensor(3.)

### Matrix-Vector Products

In [ ]:
A.shape,x.shape,torch.mv(A,x),A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

### Matrix-Matrix Multiplication

In [ ]:
B=torch.ones(3,4)
torch.mm(A,B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

### Norms

In [ ]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [ ]:
torch.abs(u).sum()

tensor(7.)

In [ ]:
# Frobenius norm
torch.norm(torch.ones((4,9)))

tensor(6.)

### Exercises

1. Prove that the transpose of the tranpose of a matrix is the matrix itself: $(A^T)^T=A$.

In [ ]:
A=torch.arange(12).reshape((3,4))
A,A.T,A.T.T,(A==A.T.T).all()

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor(True))

Let 
$$
\displaystyle
A=[[a_{1,1}, a_{1,2}, \dots, a_{1,n}], 
    \dots, 
[a_{m,1}, a_{m,2}, \dots, a_{m,n}]],
A \in \mathbb{R}^{m \times n}
$$.

Then
$$
\displaystyle
A^T=[[a_{1,1}, a_{2,1}, \dots, a_{m,1}], 
    \dots, 
[a_{1,n}, a_{2,n}, \dots, a_{m,n}]],
A^T \in \mathbb{R}^{n \times m}
$$, and
$$
\displaystyle
{A^T}^T=[[a_{1,1}, a_{1,2}, \dots, a_{1,n}], 
    \dots, 
[a_{m,1}, a_{m,2}, \dots, a_{m,n}]],
{A^T}^T \in \mathbb{R}^{m \times n}
$$

$A^T$ is the same as ${A^T}^T$. QED.

2. Given two matrices $\bold{A}$ and $\bold{B}$, show that the sum and transposition commute: $\bold{A}^T + \bold{B}^T = (A+B)^T$

Let 
$$
\displaystyle
A=[[a_{1,1}, a_{1,2}, \dots, a_{1,n}], \newline
    \vdots, \newline
[a_{m,1}, a_{m,2}, \dots, a_{m,n}]], \newline
A \in \mathbb{R}^{m \times n}
$$.

Then
$$
\displaystyle
A^T=[[a_{1,1}, a_{2,1}, \dots, a_{m,1}], \newline
    \vdots, \newline
[a_{1,n}, a_{2,n}, \dots, a_{m,n}]], \newline
A^T \in \mathbb{R}^{n \times m}
$$. 

Similarly, let 
$$
\displaystyle
B=[[b_{1,1}, b_{1,2}, \dots, b_{1,n}], \newline
    \vdots, \newline 
[b_{m,1}, b_{m,2}, \dots, b_{m,n}]], \newline
B \in \mathbb{R}^{m \times n}
$$.

Then
$$
\displaystyle
B^T=[[b_{1,1}, b_{2,1}, \dots, b_{m,1}], \newline
    \vdots, \newline
[b_{1,n}, b_{2,n}, \dots, b_{m,n}]], \newline
B^T \in \mathbb{R}^{n \times m}
$$. 

$$
\displaystyle
A^T+B^T=[[a_{1,1}+b_{1,1}, a_{2,1}+b_{2,1}, \dots, a_{m,1}+b_{m,1}], \newline
    \vdots, \newline 
[a_{1,n}+b_{1,n}, a_{2,n}+b_{2,n}, \dots, a_{m,n}+b_{m,n}]] \newline
\newline

A+B=[[a_{1,1}+b_{1,1}, a_{1,2}+b_{1,2}, \dots, a_{1,n}+b_{1,n}], \newline
    \vdots, \newline 
[a_{m,1}+b_{m,1}, a_{m,2}+b_{m,2}, \dots, a_{m,n}+b_{m,n}]] \newline
\newline
(A+B)^T=[[a_{1,1}+b_{1,1}, a_{2,1}+b_{2,1}, \dots, a_{m,1}+b_{m,1}], \newline
    \vdots, \newline 
[a_{1,n}+b_{1,n}, a_{2,n}+b_{2,n}, \dots, a_{m,n}+b_{m,n}]] \newline
\newline =A^T+B^T
$$

QED

3. Given any square matrix $\bold{A}$, is $\bold{A}+\bold{A}^T$ always symmetric? Can you prove the reuslt by using only the reuslts of the previous two exercises?

From the previous two exercises, we know ${A^T}^T=A$ and $A^T+B^T=(A+B)^T$. 

$A+A^T$ is symmetric IFF $A+A^T == (A+A^T)^T$.

We can apply the second property to decompose $(A+A^T)^T$ into $A^T+{A^T}^T$.

$$
\displaystyle
(A+A^T)^T = A^T+{A^T}^T \newline
 = A^T+A (\text{By the first property we proved})\newline 
 = A+A^T (\text{Rearrange terms})\newline 
$$

Thus, $A+A^T$ is symmetric. QED.

4. We defined the tensor X of shape (2,3,4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.

len(X) = 2 (X.shape[0])

In [ ]:
len(X)

2

5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?

Yes. len(X) always corresponds to the length of axis 0 of X.

6. Run ```A / A.sum(axis=1)``` and see what happens. Can you analyze the results?

In [ ]:
A.shape, A.sum(axis=1).shape

(torch.Size([3, 4]), torch.Size([3]))

In [ ]:
A/A.sum(axis=1)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

The operation failed as division requires both operands to have the same shape. A.sum(axis=1) reduced the first axis, meaning A and A.sum(axis=1) did not have the same shape.

7. When traveling between two points in downtown Manhattan, what is the distance that you need to conver in terms of the coordinates, i.e. in terms of avenues and streets? Can you travel diagonally?

The distance you need to cover is the Manhattan distance, or the L1 Norm of the vector representing the difference between your start and end position (AKA the sum of the absolute values of the components of the vector). You may not always be able to travel diagonally as a building may be in the way.

8. Consider a tensor of shape (2,3,4). What are the shapes of the summation outputs along axes 0, 1, and 2?

The shape of summation along axis 0 is (3,4), along axis 1 is (2,4), along axis 2 is (2,3).

In [ ]:
M = torch.arange(24).reshape((2,3,4))
M.sum(axis=0).shape, M.sum(axis=1).shape, M.sum(axis=2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

9. Feed a tensor with three or more axes to the ```linalg.norm``` function and observe its output. What does this function compute for tensors of arbitrary shape?

In [ ]:
from numpy.linalg import norm
norm(M), torch.sqrt(torch.sum(torch.square(M)))

(np.float64(65.75712889109438), tensor(65.7571))

This function computes the Frobenius/L2 norm for tensors of arbitrary shape.

10. Consider three large matrices, say $A \in \mathbb{R}^{2^{10} \times 2^{16}}$,$B \in \mathbb{R}^{2^{16} \times 2^5}$, $C \in \mathbb{R}^{2^5 \times 2^{14}}$, initialized with Gaussian random vairables. You want to compute the product $ABC$. Is there any difference in memory footprint and speed, depending on whether you compute $(AB)C$ or $A(BC)$. Why?

In a multiplication of M and N, with dimensions $m \times n$ and $n \times p$ respectively, the product is $m \times p$, and to compute each of its $mp$ entries, you need to multiply $n$ times and add. This means we have $mnp$ mutliplications and $mp$ summations.

$AB$ is $2^{10} \times 2^{5}$, so it requires $2^{10+16+5}=2^{31}$ multiplications and $2^{10+5}=2^{15}$ summations to calculate. $(AB)C$ is a further $2^{29}$ multiplications and $2^{24}$ summations, giving a total of $2^{31}+2^{29}$ multiplications and $2^{15}+2^{24}$ summations.

$BC$ is $2^{16} \times 2^{14}$, so it requires $2^{16+5+14}=2^{35}$ multiplications and $2^{16+14}=2^{30}$ summations to calculate. $A(BC)$ is a further $2^{40}$ multiplications and $2^{24}$ summations, giving a total of $2^{35}+2^{40}$ multiplications and $2^{30}+2^{24}$ summations.

$(AB)C$ requires more multiplications and summations to calculate than $A(BC)$. Thus, there is a difference in memory footprint and speed.

11. Consider three large matrices, say $A \in \mathbb{R}^{2^{10} \times 2^{16}}$,$B \in \mathbb{R}^{2^{16} \times 2^5}$, $C \in \mathbb{R}^{2^5 \times 2^{16}}$. Is there any difference in speed depending on whether you compute $AB$ or $AC^T$? Why? What changes if you initialize $C=B^T$ without cloning memory? Why?

In a multiplication of M and N, with dimensions $m \times n$ and $n \times p$ respectively, the product is $m \times p$, and to compute each of its $mp$ entries, you need to multiply $n$ times and add. This means we have $mnp$ mutliplications and $mp$ summations.

Both $AB$ and $AC^T$ are $2^{10} \times 2^{5}$, so both require $2^{10+16+5}=2^{31}$ multiplications and $2^{10+5}=2^{15}$ summations to calculate and thus should have no difference in speed depending on if $AB$ or $AC^T$ is calculated.

If we initialize $C=B^T$ without cloning memory, then $C$ is simply a lazy transpose view of $B$, where $C_{i,j}$ internally maps to $B_{j,i}$ without explicitly rearranging data in memory. While this saves space by not cloning $B$, if $B$ is stored in row-major order (i.e., row-by-row in memory), then $C$ will access its elements in column-major order, resulting in poor spatial locality and cache-unfriendly code. Thus, if we initialize $C=B^T$ without cloning memory, then $AC^T$ will be slower to compute than $AB$ due to $C$ being stored in a cache-unfriendly way.

12. Consider three matrices, say $A,B,C \in \mathbb{R}^{100 \times 200}$. Construct a tensor with three axes by stacking $[A,B,C]$. What is the dimensionality? Slice out the second coordinate of the third axis to recover $B$. Check that your answer is correct.

In [ ]:
A,B,C=torch.randn(100, 200),torch.randn(100, 200),torch.randn(100, 200)
stacked = torch.stack([A,B,C], axis=2)
stacked.shape

torch.Size([100, 200, 3])

Dimensionality is 3 (3 x 100 x 200).

In [ ]:
print("Correctly sliced out second coordinate of third axis" if (stacked[:,:,1] == B).all() else "Did not correctly slice out second coordinate of third axis")

Correctly sliced out second coordinate of third axis
