In [1]:
import torch

### 1
Run the code in this section. Change the conditional statement ```X==Y```to ```X<Y``` or ```X>Y```, and then see what kind of tensor you can get.

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [4]:
x.shape

torch.Size([12])

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3,4)

tensor([[-1.8050,  0.8338, -0.5060,  0.9899],
        [-1.3272, -0.4832,  0.6365, -1.1907],
        [-0.0477, -0.7277,  1.2713, -0.0871]])

In [9]:
torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [11]:
X[1,2]=17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
X[:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [13]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [15]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
X=torch.arange(12, dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,3,4],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  3.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X==Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum()

tensor(66.)

In [20]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b,a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

Saving Memory:

In [21]:
before=id(Y)
Y=Y+X
id(Y)==before

False

In [22]:
Z=torch.zeros_like(Y)
print(f'id(Z):{id(Z)}')
Z[:]=X+Y
print(f'id(Z):{id(Z)}')

id(Z):2714500896560
id(Z):2714500896560


Reusing X via ```X[:]``` or ```X+=Y``` for ```X+Y```

In [23]:
before=id(X)
X+=Y
id(X)==before

True

Conversion to other Python Objects

In [24]:
A=X.numpy()
B=torch.from_numpy(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

Special conversions for size-1 tensors to Python scalars

In [26]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2
Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g. 3-dimensional tensors. Is the result the same as expected?

In [29]:
a=torch.arange(3).reshape((3,1,1))
b=torch.arange(6).reshape((1,2,3))
a,b,a+b

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0, 1, 2],
          [3, 4, 5]]]),
 tensor([[[0, 1, 2],
          [3, 4, 5]],
 
         [[1, 2, 3],
          [4, 5, 6]],
 
         [[2, 3, 4],
          [5, 6, 7]]]))

In [30]:
a.shape,b.shape,(a+b).shape

(torch.Size([3, 1, 1]), torch.Size([1, 2, 3]), torch.Size([3, 2, 3]))

Yes the results were the same as expected. Both tesnors were broadcasted into the lowest dimensions possible such that the elementwise addition operation would move forward.