In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)
x.grad # None by default

In [5]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

Gradient of $\bold{y}=2\bold{x}^T\bold{x}$ should be $4\bold{x}$

In [7]:
x.grad == 4*x

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y=x.sum()
y.backward() # Gradient of y WRT x
x.grad # above gradient 

tensor([1., 1., 1., 1.])

In [ ]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x

z.sum().backward()
x.grad == u # u is a matrix, x is a vector. u is symmetric since u=x*x, so u=u^T. z=u*x so grad_x z = u^T = u

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])

In [ ]:
def f(a):
    # Defines a piecewise fn to demonstrate how PyTorch can calculate gradients no matter the control flow
    b=a*2
    while b.norm() < 1000:
        b=b*2
    if b.sum() > 0:
        c = b
    else:
        c = 100*b
    return c

In [ ]:
a=torch.randn(size=(), requires_grad=True)
d=f(a)
d.backward()

a.grad, d/a # as of 7/8/2025, torch.Tensor.__eq__() returns False if one tensor has a gradient fn and another does not

(tensor(2048.), tensor(2048., grad_fn=<DivBackward0>))