# 7.5: Pooling

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

## 7.5.1: Maximum Pooling and Average Pooling

In [ ]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i,j] = X[i:i+p_h, j:j+p_w].max() # Like a convolutional kernel but padding=0, stride=1
            elif mode == 'avg':
                Y[i,j] = X[i:i+p_h, j:j+p_w].mean()
    return Y

In [3]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2,2))

tensor([[4., 5.],
        [7., 8.]])

In [4]:
pool2d(X, (2,2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

## 7.5.2: Padding and Stride

In [5]:
X = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4)) # batch size, channels, h, w
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [ ]:
pool2d = nn.MaxPool2d(3)
pool2d(X) # default stride is 3, so we only have 1 window. within that window, largest element is 10.

tensor([[[[10.]]]])

In [ ]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2) # manually specifying pooling stride and padding
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

## 7.5.3: Multiple Channels

In [8]:
X = torch.cat((X, X+1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [ ]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X) # Still 2 channels

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

# Summary

* Pooling aggregates results over a window of values
* All convolution semantics like strides and padding apply the same way as they did previously
* Pooling is indifferent to channels
* Max pooling is preferable to average pooling as it confers some degree of invariance to output.
* Usually a 2x2 pooling window is used to quarter the spatial resolution of output